# Generated by Django 4.1.1 on 2023-01-11 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('price', models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
