# Generated by Django 4.1.1 on 2023-01-11 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lockssite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
